-------------------------


CREATE TABLE `USER_CHANGE_LOGS` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `UUID` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '康复者ID',
  `LOG_TYPE` tinyint(4) NOT NULL DEFAULT '0' COMMENT '1人员状态相关，2尿检相关',
  `CONTENT` varchar(255) NOT NULL DEFAULT '',
  `OPER_USER_ID` int(10) unsigned NOT NULL DEFAULT '0',
  `OPER_USER_NAME` varchar(16) NOT NULL DEFAULT '',
  `CREATE_TIME` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`ID`),
  KEY `UUID` (`UUID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='康复人员操作记录';

-- 新机构表
CREATE TABLE `NB_AUTH_DEPT` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `PARENTDEPTID` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '上级机构ID',
  `DEPTCODE` varchar(32) NOT NULL DEFAULT '' COMMENT '机构编码',
  `DEPTNAME` varchar(255) NOT NULL DEFAULT '' COMMENT '机构名称',
  `DEPTDESC` varchar(255) NOT NULL DEFAULT '' COMMENT '机构描述',
  `FLAG` tinyint(4) NOT NULL DEFAULT '0' COMMENT '标志，0可用，1不可用',
  `CREATOR` varchar(255) NOT NULL DEFAULT '0' COMMENT '创建人',
  `SORTORDER` int(11) NOT NULL DEFAULT '0' COMMENT '排序',
  `SERVICEPARENTDEPTID` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '上级业务ID',
  `AREACODE` varchar(32) NOT NULL DEFAULT '' COMMENT '区域代码',
  `DEPTGROUPID` int(11) NOT NULL DEFAULT '0' COMMENT '机构组ID',
  `AUTHDEPTID` int(11) NOT NULL DEFAULT '0',
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='机构表';

-- 新加表 20191124
create table BASE_USER_STATUS(
ID INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
 NAME VARCHAR(64) NOT NULL DEFAULT '',
 PRIMARY KEY(ID)
)ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='康复人员状态';

INSERT INTO `BASE_USER_STATUS` (`NAME`)
VALUES
('未报到未移交'),
('未报到已移交'),
('违反协议未移交'),
('违反协议已移交'),
('强戒中'),
('社区戒毒中'),
('社区康复中'),
('请假中'),
('社会面'),
('戒断三年未复吸'),
('社区戒毒中止'),
('社区戒毒终止')
;

create table BASE_USER_DANGER_LEVEL(
ID INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
 NAME VARCHAR(64) NOT NULL DEFAULT '',
 PRIMARY KEY(ID)
)ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='康复人员风险等级';
--
INSERT INTO `BASE_USER_DANGER_LEVEL` (`NAME`)
VALUES
('高风险'),
('中风险'),
('低风险');

create table USER_ESTIMATES(
`ID` int(10) unsigned NOT NULL AUTO_INCREMENT,
`UUID` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '康复者ID',
`DANGER_LEVEL_ID`  SMALLINT NOT NULL DEFAULT 0 comment '人员风险等级'
  `TITLE` varchar(128) NOT NULL DEFAULT '' COMMENT '标题',
  `CONTENT` text NOT NULL,
  `ADD_TIME` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `UPDATE_TIME` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`ID`),
  KEY `UUID` (`UUID`)

)ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='康复人员风险评估';

CREATE TABLE `user_users` (
  `ID` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `UUCODE` varchar(32) NOT NULL DEFAULT '' COMMENT '编号',
  `STATUS` tinyint(4) NOT NULL DEFAULT 0 COMMENT '账号状态',
  `UTYPE_ID` smallint(6) NOT NULL DEFAULT 0 COMMENT '213社戒 218社康 212是强戒',
  `NAME` varchar(16) NOT NULL DEFAULT '' COMMENT '姓名',
  `ALIAS_NAME` varchar(32) NOT NULL DEFAULT '' COMMENT '绰号',
  `GENDER` tinyint(4) NOT NULL DEFAULT 0 COMMENT '性别',
  `NATIONALITY_ID` int(11) NOT NULL DEFAULT 0,
  `NATIONALITY` varchar(16) NOT NULL DEFAULT '' COMMENT '国藉',
  `NATION_ID` int(10) unsigned NOT NULL DEFAULT 0,
  `NATION` varchar(16) NOT NULL DEFAULT '' COMMENT '民族',
  `ID_NUMBER_TYPE` int(11) NOT NULL DEFAULT 0,
  `ID_NUMBER` varchar(32) NOT NULL DEFAULT '' COMMENT '身份证号',
  `HEIGHT` smallint(5) unsigned NOT NULL DEFAULT 0 COMMENT '身高cm',
  `URAN_RATE` tinyint(4) NOT NULL DEFAULT 1 COMMENT '尿检频率:1-1次/月，2-2月/1次，3-3月/1次，4-2次/年',
  `EDUCATION_ID` smallint(5) unsigned NOT NULL DEFAULT 0,
  `EDUCATION` varchar(32) NOT NULL DEFAULT '' COMMENT '文化程度',
  `JOB_STATUS_ID` smallint(5) unsigned NOT NULL DEFAULT 0,
  `JOB_STATUS` varchar(32) NOT NULL DEFAULT '' COMMENT '就业状态',
  `MARITAL_STATUS_ID` smallint(5) unsigned NOT NULL DEFAULT 0,
  `MARITAL_STATUS` varchar(16) NOT NULL DEFAULT '' COMMENT '婚姻状况',
  `JOB_UNIT` varchar(128) NOT NULL DEFAULT '' COMMENT '工作单位',
  `MOBILE` varchar(16) NOT NULL DEFAULT '',
  `PROVINCE_ID` int(11) NOT NULL DEFAULT 0,
  `CITY_ID` int(11) NOT NULL DEFAULT 0,
  `COUNTY_ID` bigint(20) NOT NULL DEFAULT 0,
  `COUNTY_ID_12` bigint(20) NOT NULL DEFAULT 0,
  `STREET_ID` bigint(20) unsigned NOT NULL DEFAULT 0,
  `COMMUNITY_ID` bigint(20) unsigned NOT NULL DEFAULT 0,
  `DOMICILE_PLACE` varchar(64) NOT NULL DEFAULT '' COMMENT '户籍地 ',
  `DOMICILE_ADDRESS` varchar(128) NOT NULL DEFAULT '' COMMENT '户籍地详细地址 ',
  `DOMICILE_POLICE_STATION` varchar(64) NOT NULL DEFAULT '' COMMENT '户籍地派出所名称',
  `DOMICILE_POLICE_STATION_CODE` varchar(32) NOT NULL DEFAULT '' COMMENT '户籍地派出所代码',
  `LIVE_PLACE` varchar(64) NOT NULL DEFAULT '' COMMENT '居住地',
  `LIVE_ADDRESS` varchar(128) NOT NULL DEFAULT '' COMMENT '居住地详细地址',
  `LIVE_POLICE_STATION` varchar(64) NOT NULL DEFAULT '' COMMENT '居住地派出所名称 ',
  `LIVE_POLICE_STATION_CODE` varchar(32) NOT NULL DEFAULT '' COMMENT '居住地派出所代码',
  `DRUG_TYPE_ID` smallint(5) unsigned NOT NULL DEFAULT 0,
  `DRUG_TYPE` varchar(32) NOT NULL DEFAULT '' COMMENT '吸毒方式',
  `NARCOTICS_TYPE_ID` smallint(5) unsigned NOT NULL DEFAULT 0,
  `NARCOTICS_TYPE` varchar(32) NOT NULL DEFAULT '' COMMENT '毒品种类',
  `MANAGE_POLICE_AREA_CODE` varchar(16) NOT NULL DEFAULT '' COMMENT '管辖警务区代码',
  `MANAGE_POLICE_AREA_NAME` varchar(32) NOT NULL DEFAULT '' COMMENT '管辖警务区名称',
  `MANAGE_COMMUNITY` varchar(32) NOT NULL DEFAULT '' COMMENT '管辖社区',
  `POLICE_LIABLE_UID` int(11) NOT NULL DEFAULT 0,
  `POLICE_LIABLE_CODE` varchar(16) NOT NULL DEFAULT '' COMMENT '责任民警警号',
  `POLICE_LIABLE_NAME` varchar(16) NOT NULL DEFAULT '' COMMENT '责任民警姓名',
  `POLICE_LIABLE_MOBILE` varchar(16) NOT NULL DEFAULT '' COMMENT '责任民警联系电话',
  `HEAD_IMG` varchar(128) NOT NULL DEFAULT '',
  `DOMICILE_IDS` varchar(125) DEFAULT NULL,
  `UPDATE_TIME` datetime NOT NULL DEFAULT current_timestamp(),
  `ADD_TIME` datetime NOT NULL DEFAULT current_timestamp(),
  `LIVE_IDS` varchar(125) DEFAULT NULL,
  `DMMC_IDS` varchar(125) DEFAULT NULL,
  `ISDEL` tinyint(4) NOT NULL DEFAULT 0,
  `DEL_TIME` datetime DEFAULT NULL,
  `PWSD` char(33) NOT NULL DEFAULT '',
  `SALT` char(8) NOT NULL DEFAULT '',
  `CREATE_USER_ID` int(11) NOT NULL DEFAULT 0,
  `CREATE_USER_NAME` varchar(16) NOT NULL DEFAULT '',
  PRIMARY KEY (`ID`),
  UNIQUE KEY `UUCODE` (`UUCODE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='康复端账号';

-- 与省对接所需要表

-- 性别表
CREATE TABLE BASE_SEX_TYPE(
ID INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
 NAME VARCHAR(64) NOT NULL DEFAULT '',
 PRIMARY KEY(ID)
)ENGINE=INNODB DEFAULT CHARSET=UTF8 COMMENT='性别表';

-- 国籍表
CREATE TABLE BASE_NATIONALITY_TYPE(
ID INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
 NAME VARCHAR(64) NOT NULL DEFAULT '',
 PRIMARY KEY(ID)
)ENGINE=INNODB DEFAULT CHARSET=UTF8 COMMENT='国籍表';

-- 民族表
CREATE TABLE BASE_NATION_TYPE(
ID INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
 NAME VARCHAR(64) NOT NULL DEFAULT '',
 PRIMARY KEY(ID)
)ENGINE=INNODB DEFAULT CHARSET=UTF8 COMMENT='民族表';

-- 婚姻状况表
CREATE TABLE BASE_MARRY_TYPE(
ID INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
 NAME VARCHAR(64) NOT NULL DEFAULT '',
 PRIMARY KEY(ID)
)ENGINE=INNODB DEFAULT CHARSET=UTF8 COMMENT='婚姻状况表';

-- 证件种类表
CREATE TABLE BASE_CERTIFICATE_TYPE(
ID INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
 NAME VARCHAR(64) NOT NULL DEFAULT '',
 PRIMARY KEY(ID)
)ENGINE=INNODB DEFAULT CHARSET=UTF8 COMMENT='证件种类表';

-- 文化程度表
CREATE TABLE BASE_CULTURE_TYPE(
ID INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
 NAME VARCHAR(64) NOT NULL DEFAULT '',
 PRIMARY KEY(ID)
)ENGINE=INNODB DEFAULT CHARSET=UTF8 COMMENT='文化程度表';

-- 就业情况表
CREATE TABLE BASE_WORKINFO_TYPE(
ID INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
 NAME VARCHAR(64) NOT NULL DEFAULT '',
 PRIMARY KEY(ID)
)ENGINE=INNODB DEFAULT CHARSET=UTF8 COMMENT='就业情况表';

-- 从业情况表
CREATE TABLE BASE_WORK_STATUS(
 ID INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
 NAME VARCHAR(64) NOT NULL DEFAULT '',
 PRIMARY KEY(ID)
)ENGINE=INNODB DEFAULT CHARSET=UTF8 COMMENT='从业情况表';



-- 机构表
CREATE TABLE NB_AUTH_DEPT(
ID INT NOT NULL AUTO_INCREMENT,
PARENTDEPTID INT(10) UNSIGNED NOT NULL DEFAULT '0' COMMENT '上级机构ID',
DEPTCODE VARCHAR(32) NOT NULL DEFAULT '' COMMENT '机构编码',
DEPTNAME VARCHAR(255) NOT NULL DEFAULT '' COMMENT '机构名称',
DEPTDESC VARCHAR(255) NOT NULL DEFAULT '' COMMENT '机构描述',
FLAG TINYINT NOT NULL DEFAULT '0' COMMENT '标志',
CREATOR VARCHAR(255) NOT NULL DEFAULT '0' COMMENT '创建人',
SORTORDER INT NOT NULL DEFAULT 0 COMMENT '排序',
SERVICEPARENTDEPTID INT UNSIGNED NOT NULL DEFAULT '0' COMMENT '上级业务ID',
AREACODE VARCHAR(32) NOT NULL DEFAULT '' COMMENT '区域代码',
DEPTGROUPID INT  NOT NULL DEFAULT '0' COMMENT '机构组ID',
AUTHDEPTID INT  NOT NULL DEFAULT '0',
PRIMARY KEY(ID)
)ENGINE=INNODB DEFAULT CHARSET=UTF8 COMMENT='机构表';

-- 地区编码表
CREATE TABLE `UPAREATABLE` (
  `UPAREAID` char(7) NOT NULL,
  `UPTYPE` int(11) DEFAULT NULL COMMENT '类型',
  `RELATEID` varchar(16) NOT NULL DEFAULT '',
  `UPAREANAME` varchar(128) NOT NULL DEFAULT '' COMMENT '地区名称',
  `UPCORPNAME` varchar(128) NOT NULL DEFAULT '',
  `FLAG` tinyint(4) NOT NULL DEFAULT '0' COMMENT '标志，有效性',
  `TASKFLAG` tinyint(4) DEFAULT NULL,
  `LISTORDER` int(11) NOT NULL DEFAULT '0',
  `REMARKSTR` varchar(128) NOT NULL DEFAULT '' COMMENT '备注',
  `PROVINCEID` varchar(12) NOT NULL DEFAULT '' COMMENT '所属省编码',
  `PROVINCENAME` varchar(128) NOT NULL DEFAULT '' COMMENT '所属省名称',
  `CITYID` varchar(12) NOT NULL DEFAULT '' COMMENT '所属城市编码',
  `CITYNAME` varchar(128) NOT NULL DEFAULT '' COMMENT '所属城市名称',
  `TELCODE` varchar(16) NOT NULL DEFAULT '' COMMENT '区号',
  `NAME` varchar(32) NOT NULL DEFAULT '' COMMENT '名称',
  `PID` int(11) NOT NULL DEFAULT '0',
  PRIMARY KEY (`UPAREAID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='地区编码表';

CREATE TABLE SUBAREAS(
ID BIGINT NOT NULL AUTO_INCREMENT,
CODE12 BIGINT NOT NULL DEFAULT 0 COMMENT '十二位区划代码',
COUNTRY_CODE VARCHAR(8)  NOT NULL DEFAULT '' COMMENT '乡村属性代码',
CITY_COUNTRY_CODE VARCHAR(8)  NOT NULL DEFAULT '' COMMENT '城乡分类代码',
NAME VARCHAR(128) NOT NULL DEFAULT '' COMMENT '区划名称',
PROVICEID  BIGINT NOT NULL DEFAULT 0 COMMENT '省ID',
CITYID BIGINT NOT NULL DEFAULT 0 COMMENT '市ID',
COUNTYID BIGINT NOT NULL DEFAULT 0 COMMENT '县ID',
PID BIGINT NOT NULL DEFAULT 0 COMMENT '上级ID',
PRIMARY KEY(ID),
KEY(CODE12),
KEY(PROVICEID,CITYID,COUNTYID),
KEY(PID)
)ENGINE=INNODB DEFAULT CHARSET=UTF8 COMMENT='城乡地区编码表';


CREATE TABLE B_XDRY(
ID  BIGINT NOT NULL AUTO_INCREMENT,
JD_USER_USER_ID INT NOT NULL DEFAULT 0 COMMENT '康复人员表中的id',
N_XH VARCHAR(32) NOT NULL DEFAULT '' COMMENT '吸毒人员序号（主键）',
C_XDRYLX VARCHAR(32) NOT NULL DEFAULT '' COMMENT '人员类型',
C_RYBH VARCHAR(32) NOT NULL DEFAULT '' COMMENT '人员编号',
C_TNAME TINYINT COMMENT '业务类型（1：社区戒毒  2：社区康复，3：强制隔离戒毒）',
C_XM VARCHAR(32) NOT NULL DEFAULT '' COMMENT '姓名',
C_CH VARCHAR(32) NOT NULL DEFAULT '' COMMENT '绰号/别名',
C_SFZJZL VARCHAR(32) NOT NULL DEFAULT '' COMMENT '证件种类 ',
C_18SFZHM VARCHAR(32) NOT NULL DEFAULT '' COMMENT '18位身份证号',
C_WHCD INT NOT NULL DEFAULT 0 COMMENT '文化程度',
C_FWCS VARCHAR(32) NOT NULL DEFAULT '' COMMENT '工作单位',
C_JYQK INT NOT NULL DEFAULT 0 COMMENT '就业情况',
C_XDHGST VARCHAR(32) NOT NULL DEFAULT '' COMMENT '指纹编号',
C_DNA VARCHAR(32) NOT NULL DEFAULT '' COMMENT 'DNA编号',
D_DJ DATETIME COMMENT '录入日期',
C_ZJLX VARCHAR(32) NOT NULL DEFAULT '' COMMENT '证件类型',
C_SFZHM  VARCHAR(32) NOT NULL DEFAULT '' COMMENT '身份证号',
C_SJHM  VARCHAR(32) NOT NULL DEFAULT '' COMMENT '身份证号',
C_HJSZD  VARCHAR(32) NOT NULL DEFAULT '' COMMENT '户籍所在地',
C_HJSZDXZ VARCHAR(32) NOT NULL DEFAULT '' COMMENT '户籍所在地行政区划',
C_HJPCS VARCHAR(32) NOT NULL DEFAULT '' COMMENT '户籍地派出所',
C_SJJZD VARCHAR(32) NOT NULL DEFAULT '' COMMENT '实际居住地',
C_SJJZDXZ VARCHAR(32) NOT NULL DEFAULT '' COMMENT '实际居住地祥址',
C_SJPCS VARCHAR(32) NOT NULL DEFAULT '' COMMENT '实际居住地派出所',
C_XB INT NOT NULL DEFAULT 0 COMMENT '性别',
D_CS DATE COMMENT '出生日期',
C_MZ INT NOT NULL DEFAULT 0 COMMENT '民族',
N_SG SMALLINT NOT NULL DEFAULT 0 COMMENT '身高',
C_GJ INT NOT NULL DEFAULT 0 COMMENT '国籍',
C_CZBS  VARCHAR(32) NOT NULL DEFAULT '' COMMENT '操作标识',
C_CYZK INT NOT NULL DEFAULT 0 COMMENT '从业状况',
C_HY INT NOT NULL DEFAULT 0 COMMENT '婚姻状况',
C_DJR INT NOT NULL DEFAULT 0 COMMENT '录入人',
C_TBDW VARCHAR(32) NOT NULL DEFAULT '' COMMENT '填表单位',
C_TBR VARCHAR(32) NOT NULL DEFAULT '' COMMENT '填表人',
C_GSDW VARCHAR(32) NOT NULL DEFAULT '' COMMENT '归属单位',
SYS_DATAFROM INT NOT NULL DEFAULT 0 COMMENT '数据来源（1,3-法制处置记录 5-外省处置记录  2-动态管控接管）',
INPUTTIME DATETIME COMMENT '录入时间',
UPDATETIME DATETIME COMMENT '更新时间',
N_YXX TINYINT COMMENT '有效性',
PRIMARY KEY (ID)
)ENGINE=INNODB DEFAULT CHARSET=UTF8 COMMENT='吸毒人员表';


--------------------------

CREATE TABLE USER_PHONE_DATA_SMS(
ID INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
UUID INT(10) UNSIGNED NOT NULL DEFAULT '0' COMMENT '康复者ID',
TYPE VARCHAR(16) NOT NULL DEFAULT '',
ADDRESS VARCHAR(64) NOT NULL DEFAULT '',
PERSON INT(10) UNSIGNED NOT NULL DEFAULT '0',
NUMBER VARCHAR(64) NOT NULL DEFAULT '',
SMS_DATE DATETIME,
BODY TEXT,
ADD_TIME DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
PRIMARY KEY (`ID`),
KEY(UUID)
)ENGINE=MYISAM DEFAULT CHARSET=UTF8 COMMENT='用户短信记录';

CREATE TABLE USER_PHONE_DATA_ADDRESS(
ID INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
UUID INT(10) UNSIGNED NOT NULL DEFAULT '0' COMMENT '康复者ID',
NAME VARCHAR(64) NOT NULL DEFAULT '',
NUMBER VARCHAR(64) NOT NULL DEFAULT '',
UPDATE_TIME DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
PRIMARY KEY (`ID`),
KEY(UUID)
)ENGINE=MYISAM DEFAULT CHARSET=UTF8 COMMENT='用户通讯录';


CREATE TABLE USER_PHONE_DATA_CALLS(
ID INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
UUID INT(10) UNSIGNED NOT NULL DEFAULT '0' COMMENT '康复者ID',
CALL_NAME VARCHAR(64) NOT NULL DEFAULT '',
CALL_NUMBER VARCHAR(64) NOT NULL DEFAULT '',
CALL_TYPE_STR VARCHAR(32) NOT NULL DEFAULT '',
CALL_DATE_STR VARCHAR(32) NOT NULL DEFAULT '',
CALL_DATE DATE,
CALL_TIME VARCHAR(16) NOT NULL DEFAULT '',
CALL_DURATION_STR VARCHAR(64) NOT NULL DEFAULT '',
ADD_TIME DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
PRIMARY KEY (`ID`),
KEY(UUID)

)ENGINE=MYISAM DEFAULT CHARSET=UTF8 COMMENT='用户通话记录';



CREATE TABLE AGREEMENTS(
`ID` int(10) unsigned NOT NULL AUTO_INCREMENT,
`UUID` INT(10) UNSIGNED NOT NULL DEFAULT '0' COMMENT '康复者ID',
TITLE varchar(128) NOT NULL DEFAULT '' COMMENT '标题',
CONTENT TEXT NOT NULL,
ADD_TIME datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
UPDATE_TIME datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
PRIMARY KEY (`ID`),
key(UUID)
)ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='康复协议';


CREATE TABLE `CAROUSELS` (
  `ID` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `CLIENT_TAG` tinyint(4) NOT NULL DEFAULT '3' COMMENT '客户端标记：1康复端,2管理端,3全部',
  `POS` tinyint(4) NOT NULL DEFAULT '1' COMMENT '展示的位置，1APP首页，2扩展',
  `STABLE` varchar(16) NOT NULL DEFAULT '' COMMENT '资源所在的表',
  `SID` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '资源的ID',
  `TYPE` tinyint(4) NOT NULL DEFAULT '2' COMMENT '内容类型，1文字，2图片，3图文',
  `TITLE` varchar(64) NOT NULL DEFAULT '' COMMENT '静态类型-标题',
  `IMG` varchar(128) NOT NULL DEFAULT '' COMMENT '静态类型-LOGO',
  `JUMP_LINK` varchar(128) NOT NULL DEFAULT '' COMMENT '静态类型-链接',
  `ORDERID` tinyint(4) NOT NULL DEFAULT '0',
  `BEGIN_TIME` datetime DEFAULT NULL COMMENT '开始时间',
  `END_TIME` datetime DEFAULT NULL COMMENT '结束时间',
  `ADD_TIME` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '添加时间',
  `ISDEL` tinyint(4) NOT NULL DEFAULT '0',
  `DEL_TIME` datetime DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `CLIENT_POS` (`CLIENT_TAG`,`POS`)
) ENGINE=InnoDB AUTO_INCREMENT=14 DEFAULT CHARSET=utf8 COMMENT='轮播表';


CREATE TABLE HELPER_DIARYS(
`ID` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
UMID INT(11) NOT NULL DEFAULT '0' COMMENT '管理端用户ID',
UUID INT(11) NOT NULL DEFAULT '0' COMMENT '康复端用户ID',
ADD_YEAR SMALLINT NOT NULL DEFAULT 2019,
ADD_MONTH TINYINT NOT NULL ,
ADD_DAY TINYINT NOT NULL ,
TITLE VARCHAR(225) NOT NULL DEFAULT '',
CONTENT TEXT NOT NULL,
ADD_TIME DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
PRIMARY KEY(ID),
KEY (UMID),
KEY (UUID),
KEY YEAR_MONTH(ADD_YEAR,ADD_MONTH)

)ENGINE=INNODB DEFAULT CHARSET=UTF8 COMMENT='帮扶日记';


CREATE TABLE `HELPER_AREAS` (
  `ID` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `UMID` INT(10) UNSIGNED NOT NULL DEFAULT '0' COMMENT '管理端账号ID',
  `PROVINCE_ID` INT(10) UNSIGNED NOT NULL DEFAULT '0',
  `CITY_ID` INT(10) UNSIGNED NOT NULL DEFAULT '0',
  `COUNTY_ID` INT(10) UNSIGNED NOT NULL DEFAULT '0',
  `STREET_ID` INT(10) UNSIGNED NOT NULL DEFAULT '0',
  `COMMUNITY_ID` INT(10) UNSIGNED NOT NULL DEFAULT '0',
  `LEVEL` VARCHAR(32) NOT NULL DEFAULT '0' COMMENT '1市级，2县区级，3街道级，4社区级',
  `AREA_IDS` TEXT COMMENT '地区ID字符串',
  `UPDATE_TIME` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`ID`),
  KEY `UMID` (`UMID`)
) ENGINE=INNODB DEFAULT CHARSET=UTF8 COMMENT='管理端帮扶辖区配置表';



CREATE TABLE `SYSTEM_MESSAGES` (
  `ID` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `CLIENT_TAG` tinyint(4) NOT NULL DEFAULT '0' COMMENT '客户端标记：0个人,1康复端,2管理端,3全部',
  `CLIENT_UID` int(11) NOT NULL DEFAULT '0' COMMENT '客户端用户id',
  `TITLE` varchar(225) NOT NULL DEFAULT '',
  `CONTENT` text,
  `ADD_TIME` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`ID`),
  key(CLIENT_TAG)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='系统消息';

CREATE TABLE `SYSTEM_MESSAGE_READ` (
  `ID` int(10) unsigned NOT NULL AUTO_INCREMENT,
  MSGID` int(11) NOT NULL DEFAULT '0' COMMENT '消息id',
  `CLIENT_TAG` tinyint(4) NOT NULL DEFAULT '0' COMMENT '客户端标记：0个人,1康复端,2管理端,3全部',
  `CLIENT_UID` int(11) NOT NULL DEFAULT '0' COMMENT '客户端用户id',
  ISREAD  tinyint(4) NOT NULL DEFAULT '0',
  READ_TIME datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`ID`),
  key msg_client_uid (MSGID,CLIENT_UID,CLIENT_TAG)

  )ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='系统消息';


CREATE TABLE `ADMIN_ACCESS` (
  `ROLE_ID` SMALLINT(6) UNSIGNED NOT NULL DEFAULT '0' COMMENT '角色ID',
  `NODE_ID` SMALLINT(6) UNSIGNED NOT NULL DEFAULT '0',
  KEY `GROUPID` (`ROLE_ID`),
  KEY `NODEID` (`NODE_ID`)
) ENGINE=INNODB DEFAULT CHARSET=UTF8 COMMENT='权限配置表';

CREATE TABLE `ADMINS` (
  `ID` SMALLINT(6) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'ID',
  `LOG` VARCHAR(20) NOT NULL DEFAULT '' COMMENT '账号',
  `PWD` VARCHAR(32) NOT NULL DEFAULT '' COMMENT '密码',
  `STAT` CHAR(5) NOT NULL DEFAULT '' COMMENT '随机码',
  `ROLE_ID` INT(11) NOT NULL DEFAULT '0' COMMENT '角色ID',
  `ROLE` VARCHAR(10) NOT NULL DEFAULT '' COMMENT '角色名',
  `NAME` VARCHAR(16) NOT NULL DEFAULT '' COMMENT '姓名',
  `MOBILE` VARCHAR(15) NOT NULL DEFAULT '',
  `HEAD_IMG` VARCHAR(128) NOT NULL DEFAULT '' COMMENT '头像',
  `GENDER` TINYINT(1) NOT NULL DEFAULT '0' COMMENT '性别:0未知，1男，2女',
  `IS_WORK` TINYINT(4) NOT NULL DEFAULT '1' COMMENT '是否在职',
  `STATUS` TINYINT(4) NOT NULL DEFAULT '1' COMMENT '登录控制',
  `DMMC_ID` SMALLINT(6) UNSIGNED NOT NULL DEFAULT '0' COMMENT '部门ID',
  `DMMC_NAME` VARCHAR(20) NOT NULL DEFAULT '' COMMENT '部门名称',
  `LOGINIP` VARCHAR(64) NOT NULL DEFAULT '' COMMENT '最近登录IP',
  `LGTIME` INT(10) UNSIGNED NOT NULL DEFAULT '0' COMMENT '最近登录时间',
  `POST` VARCHAR(20) NOT NULL DEFAULT '' COMMENT '职位',
  `CONTACT` VARCHAR(100) NOT NULL DEFAULT '' COMMENT '其他联系方式',
  `REMARK` VARCHAR(255) NOT NULL DEFAULT '' COMMENT '备注信息',
  `ADD_TIME` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '添加时间',
  `ISDEL` TINYINT(4) NOT NULL DEFAULT '0' COMMENT '删除标记',
  PRIMARY KEY (`ID`),
  KEY `ROLE_ID` (`ROLE_ID`)
) ENGINE=INNODB AUTO_INCREMENT=122 DEFAULT CHARSET=UTF8 COMMENT='后台用户表';

CREATE TABLE `ADMIN_NODES` (
  `ID` SMALLINT(6) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '节点ID',
  `NAME` VARCHAR(20) NOT NULL COMMENT '节点名字',
  `TITLE` VARCHAR(50) DEFAULT '' COMMENT '节点中文名称',
  `STATUS` TINYINT(4) DEFAULT '1' COMMENT '状态，0隐藏，1显示',
  `REMARK` VARCHAR(255) DEFAULT '' COMMENT '备注说明 ',
  `SORT` SMALLINT(6) UNSIGNED DEFAULT '0' COMMENT '排序',
  `PID` SMALLINT(6) UNSIGNED NOT NULL COMMENT '父节点',
  `GID` SMALLINT(6) NOT NULL DEFAULT '0' COMMENT '分组ID',
  `LEVEL` TINYINT(1) UNSIGNED NOT NULL COMMENT '级别',
  `ISMENU` TINYINT(4) NOT NULL DEFAULT '0' COMMENT '是否用为菜单',
  `ICON` VARCHAR(32) NOT NULL DEFAULT '' COMMENT '图标',
  `ADD_TIME` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '添加时间',
  PRIMARY KEY (`ID`),
  KEY `PID` (`PID`),
  KEY `GID` (`GID`),
  KEY `STATUS` (`STATUS`),
) ENGINE=INNODB  DEFAULT CHARSET=UTF8  COMMENT='权限节点表';


CREATE TABLE `ADMIN_NODE_GROUPS` (
  `ID` SMALLINT(6) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'ID',
  `NAME` VARCHAR(15) NOT NULL DEFAULT '' COMMENT '组名',
  `ICON` VARCHAR(32) NOT NULL DEFAULT '' COMMENT '图标',
  `LINK` VARCHAR(32) NOT NULL DEFAULT '' COMMENT '分组默认链接',
  `SORT` SMALLINT(6) UNSIGNED NOT NULL DEFAULT '1' COMMENT '排序',
  PRIMARY KEY (`ID`)
) ENGINE=INNODB DEFAULT CHARSET=UTF8 COMMENT='菜单分组表';

CREATE TABLE `ADMIN_LOGS` (
  `ID` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `USER_ID` INT(10) UNSIGNED NOT NULL DEFAULT '0',
  `USER_NAME` VARCHAR(32) NOT NULL DEFAULT '' COMMENT '操作人信息',
  `CONTENT` VARCHAR(225) NOT NULL DEFAULT '' COMMENT '操作事项',
  `URL` VARCHAR(225) NOT NULL DEFAULT '',
  `IP` VARCHAR(32) NOT NULL DEFAULT '',
  `ADD_TIME` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`ID`),
  KEY `USER_ID` (`USER_ID`)
) ENGINE=INNODB DEFAULT CHARSET=UTF8 COMMENT='后台管理人员操作日志';

CREATE TABLE `ADMIN_ROLES` (
  `ID` SMALLINT(6) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'ID',
  `NAME` VARCHAR(20) NOT NULL COMMENT '角色名',
  `PID` SMALLINT(6) NOT NULL DEFAULT '0' COMMENT '父ID（未使用）',
  `STATUS` TINYINT(4) NOT NULL DEFAULT '1' COMMENT '状态，0禁用，1启用',
  `REMARK` VARCHAR(255) NOT NULL DEFAULT '' COMMENT '备注说明',
  `ADD_TIME` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`ID`),
  KEY `PID` (`PID`),
  KEY `STATUS` (`STATUS`)
) ENGINE=INNODB DEFAULT CHARSET=UTF8 COMMENT='角色表';